Feat on resolvers called top level
graphql-hive/envelop pull request #1236
Opened 2022-01-27 11:51 UTC by n1ru4l

2022-01-27 11:52 UTC, dotansimha approved these changes

2022-01-27 11:57 UTC, kamilkisiela approved these changes

2022-01-27 12:20 UTC, n1ru4l commented on .changeset/fresh-toes-hang.md
> +import type { Plugin } from "@envlop/core";
```suggestion
import type { Plugin } from "@envelop/core";
```

2022-01-27 12:20 UTC, n1ru4l commented on .changeset/fresh-toes-hang.md
> +import type { Plugin } from '@envlop/core';
```suggestion
import type { Plugin } from '@envelop/core';
```

2022-01-28 02:27 UTC, saihaj requested changes
need to update site https://www.envelop.dev/docs/plugins/lifecycle#plugins-api

2022-01-28 13:11 UTC, n1ru4l commented
@saihaj done 🥳

2022-01-28 13:33 UTC, saihaj approved these changes

2022-02-01 19:08 UTC, merged