useGraphQlJit: Add option to pass in custom cache instance
graphql-hive/envelop pull request #1318
Opened 2022-03-11 14:57 UTC by dios-david

## Description

Hey again! Following my previous changes [here](https://github.com/dotansimha/envelop/pull/741) I would like to do a similar thing with the graphql-jit plugin as well.

Fixes https://github.com/dotansimha/envelop/issues/1317

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [x] `packages/plugins/graphql-jit/test/graphql-jit.spec.ts`

**Test Environment**:

- OS: macOS 12.2.1
- `@envelop/...`: latest
- NodeJS: v16.14.0

## Checklist:

- [x] I have followed the [CONTRIBUTING](https://github.com/the-guild-org/Stack/blob/master/CONTRIBUTING.md) doc and the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented on my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

## Further comments

If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc...

2022-03-12 06:43 UTC, saihaj approved these changes

2022-03-12 21:59 UTC, n1ru4l requested changes
I have the same concerns about the max and ttl option I mentioned over here: https://github.com/dotansimha/envelop/pull/741#discussion_r721958719

2022-03-13 07:53 UTC, dotansimha approved these changes

2022-03-13 13:40 UTC, dios-david commented
@n1ru4l @dotansimha I created another PR with the addition of removing the `max` and the `ttl` options, and bumping the major instead. This makes it more consistent with `useParserCache` and `useValidationCache`.

https://github.com/dotansimha/envelop/pull/1321/files

Feel free to close one of these.

2022-03-14 12:20 UTC, n1ru4l commented
closed in favor of https://github.com/dotansimha/envelop/pull/1321

2022-03-14 12:20 UTC, closed without merging