feat: add tracing data to transaction
graphql-hive/envelop pull request #1420
Opened 2022-06-18 15:15 UTC by mmahalwy

🚨 **IMPORTANT: Please do not create a Pull Request without creating an issue first.**

_Any change needs to be discussed before proceeding. Failure to do so may result in the rejection of the pull request._

## Description

This PR adds the ability to manually instrument the transaction with tracing data. This is taken from the express handler, see: https://github.com/getsentry/sentry-javascript/blob/master/packages/node/src/handlers.ts#L44

Fixes # (issue)

## Type of change
Feature 

Please delete options that are not relevant.

- [x] New feature (non-breaking change which adds functionality)

## Screenshots/Sandbox (if appropriate/relevant):

None

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

**Test Environment**:

- OS:
- `@envelop/...`:
- NodeJS:

## Checklist:

- [x] I have followed the [CONTRIBUTING](https://github.com/the-guild-org/Stack/blob/master/CONTRIBUTING.md) doc and the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented on my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

## Further comments

If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc...

2022-06-18 23:27 UTC, saihaj approved these changes

2022-06-19 08:48 UTC, n1ru4l requested changes
Can you please update the documentation for showing how this feature can be used? Also can you please add a changeset?

2022-06-20 22:02 UTC, mmahalwy commented
@n1ru4l will do.

2022-06-22 18:20 UTC, mmahalwy commented
@n1ru4l lmk if that is helpful

2022-06-27 10:27 UTC, n1ru4l commented
@mmahalwy Can you please also create a changeset via `yarn changeset`? Sorry, after transferring the repository we forgot to reenable the changeset bot.

2022-06-27 17:46 UTC, mmahalwy commented
@n1ru4l how about now?

2022-06-27 18:08 UTC, saihaj commented on .changeset/nasty-nails-occur.md
> +'@envelop/sentry': major
```suggestion
'@envelop/sentry': minor
```

2022-06-27 18:08 UTC, saihaj commented on .changeset/nasty-nails-occur.md
> +Added tracing for sentry
can you also give an example here so it is documented in part of changelog on how user can utilize this feature.

2022-06-27 19:55 UTC, mmahalwy commented on .changeset/nasty-nails-occur.md
> +Added tracing for sentry
@saihaj its in the documentation.

2022-06-27 19:56 UTC, mmahalwy commented
@n1ru4l @saihaj updated.

2022-06-27 20:36 UTC, saihaj approved these changes

2022-06-27 20:45 UTC, n1ru4l approved these changes

2022-06-27 20:45 UTC, merged