give access to execute args in generic auth plugin
graphql-hive/envelop pull request #1528
Opened 2022-09-17 15:55 UTC by EmrysMyrddin

## Description

This PR aims to give more flexibility to the user validation of the generic-auth plugin byt giving access to the execute args.
This would give access to context and variables of the operation.

Fixes #1527

## Type of change

Please delete options that are not relevant.

- [x] New feature (non-breaking change which adds functionality)

## How Has This Been Tested?

I have published this PR as `@emrys-myrddin/envelop-generic-auth@4.5.0-fork.1` and tested it on my company's project.
I was able to build a plugin leading to the api I have describe in the issue #1527.

**Test Environment**:

- OS: macOS 12.5.1
- `@envelop/generic-auth`: v4.5.0
- NodeJS: v16.14.0

## Checklist:

- [x] I have followed the [CONTRIBUTING](https://github.com/the-guild-org/Stack/blob/master/CONTRIBUTING.md) doc and the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented on my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
  - The documentation is not very exhaustive on available arguments, I'm not sure it is needed to modify it. I've just updated code documentation.
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
  - Not sure any test are needed here since types already ensure that this works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

2022-09-19 07:27 UTC, n1ru4l commented on packages/plugins/generic-auth/src/index.ts
> +                    args,
Can we give this a better naming like `executionArgs`?

2022-09-19 07:27 UTC, n1ru4l requested changes
Only a small renaming thing, please also update the corresponding documentation and add an example to the changeset ☺️

2022-09-19 15:09 UTC, EmrysMyrddin commented
Where should I add documentation and example for this ?

2022-09-19 15:19 UTC, n1ru4l commented
@EmrysMyrddin This is the plugin documentation: https://www.envelop.dev/plugins/use-generic-auth

2022-09-19 15:22 UTC, EmrysMyrddin commented
So you want me to add a section after https://www.envelop.dev/plugins/use-generic-auth#extend-authentication-with-custom-directive-logic with an example usage of the execution arguments ?

2022-09-19 15:24 UTC, n1ru4l commented
Yes and please also update the changeset to give an code example as well as mention a possible use-case where this is helpful.

2022-09-20 07:36 UTC, EmrysMyrddin commented
I'm not sure to understand what you mean by this sorry. I can add examples to the changeset ? It's not just a short descripion of my changement ?

2022-09-20 07:42 UTC, n1ru4l commented
@EmrysMyrddin You can add a code block example to the changeset, like the following: https://github.com/n1ru4l/envelop/blob/main/packages/core/CHANGELOG.md#minor-changes-7

Just the changelog entry `give access to execute args in generic auth plugin` won't show people how they can now use this.

2022-09-20 08:05 UTC, EmrysMyrddin commented
Ho ok that's really nice. I have added the changeset doc + updated the documentation (with some little refactoring to make the "custom logic" part more clear)

2022-09-20 08:33 UTC, EmrysMyrddin commented
Writing the documentation made me wondering if the custom per field validation couldn't be directly implemented by the plugin ? I suppose validating a field with arguments against the user is pretty common.

2022-09-22 09:01 UTC, n1ru4l approved these changes

2022-09-22 09:01 UTC, n1ru4l commented
> Writing the documentation made me wondering if the custom per field validation couldn't be directly implemented by the plugin ? I suppose validating a field with arguments against the user is pretty common.

That is something open for discussion and out of scope of this PR!

2022-09-22 09:01 UTC, merged