check for subscriptions
graphql-hive/envelop pull request #1921
Opened 2023-08-05 17:27 UTC by don-cryptus

🚨 **IMPORTANT: Please do not create a Pull Request without creating an issue first.**

_Any change needs to be discussed before proceeding. Failure to do so may result in the rejection of
the pull request._

## Description

The onParse method has been modified to address an issue where it was adding a __typename field to all operations, including subscriptions. This was leading to disruptions in subscriptions as they were not designed to recognize or process this field. To resolve this, a check has been implemented to determine if the call is a subscription before proceeding.

Fixes # (issue)
https://github.com/n1ru4l/envelop/issues/1920

## Type of change

Please delete options that are not relevant.

- [x ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as
      expected)
- [ ] This change requires a documentation update

## Screenshots/Sandbox (if appropriate/relevant):

[Stackblitz](https://stackblitz.com/edit/node-dazht5?file=src%2Fapp.module.ts)

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can
reproduce. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

**Test Environment**:

- OS: Windows
- `@envelop/4`:
- NodeJS: 18

## Checklist:

- [x] I have followed the
      [CONTRIBUTING](https://github.com/the-guild-org/Stack/blob/master/CONTRIBUTING.md) doc and the
      style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented on my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

## Further comments

2023-08-17 09:23 UTC, n1ru4l approved these changes

2023-08-17 09:25 UTC, n1ru4l requested changes
Can you add another test case for the following document:

```graphql
query Foo {
  comment
}

subscription Sub {
  comment
}
```

And `operationName` "Sub" in the graphql request?

2023-08-19 21:57 UTC, don-cryptus commented
While integrating the recent changes, I noticed a behavior where the onParse function was modifying documents that contained subscriptions. This led to unexpected results, especially when the documents had mixed queries and subscriptions.

In this pull request, I've made adjustments to the onParse function to ensure that if a GraphQL document contains a subscription, it's not modified. This change has been thoroughly tested, and I can confirm that it works correctly with both the old and new test cases.

2023-09-27 21:52 UTC, ardatan commented
Thanks for the PR and the issue! It's fixed in https://github.com/n1ru4l/envelop/pull/1956

2023-09-27 21:52 UTC, closed without merging