always eagerly check if cache is enable for the current request
graphql-hive/envelop pull request #1977
Opened 2023-10-02 13:20 UTC by EmrysMyrddin

## Description

The `enabled` parameter allows the user to disabled the cache at a request level based on the context. This give the user fine grain control of the cache behaviour.

But the current implementation only allow to disabled **reading** from the cache. The rest of the pipeline is still executed, the request result will still be written to the cache, and it will still invalidate the cache.

This PR aims to modify this behaviour by using `enabled` to entirely disable the cache. For this, I check as eagerly as possible the `enabled` function to stop the cache related processing as soon as possible.

Fixes #1963 

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)

## More Context

I'm not sure if I should entirely disable the cache, or if we should still always do the automatic invalidation. Or perhaps having 2 options to control this 2 features separately ?

2023-10-02 13:23 UTC, EmrysMyrddin commented
I'm not sure if this is considered a breaking change and if we should do a major version to release this.

If we think it's breaking a breaking change, we should consider shipping #1939 too.

2023-10-02 21:47 UTC, n1ru4l requested changes
Can we also add tests for this, to catch regressions?
Technically, this is also a breaking change, so let's release this as a major version with a changeset.

2023-10-09 15:24 UTC, EmrysMyrddin commented
@n1ru4l Do you think the test is sufficient ? I was not sure how to test this, so i just tested that the cache object is not used when `enabled` return false.

2023-10-14 00:24 UTC, ardatan approved these changes

2023-10-16 07:58 UTC, merged